const Items = [
  {
    id: 1,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369315/My_Favorite_Recipe_Page_fgtgdf.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369315/My_Favorite_Recipe_Page_fgtgdf.png",
    ],
    features: [
      "Basic HTML Structure",
      "Headings (h1, h2, h3)",
      "Paragraphs",
      "Line Breaks",
      "Text Formatting Tags",
      "Lists",
      "Horizontal Lines",
    ],
    technologies: [
      "HTML",
    ],
    title: "My Favorite Recipe Page",
    description:
      "This project is a simple HTML based recipe page that displays the steps to make a delicious chocolate cake. It includes well-structured sections such as ingredients, preparation steps, and helpful baking tips. The page uses basic HTML elements like headings, lists, text formatting tags, and separators to present the recipe clearly and neatly. It serves as a beginner-friendly example of organizing content using semantic HTML.",
    category: "html",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/My_Favourite_Recipe_Page_H",
  },
  {
    id: 2,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369314/My_Favorite_Movie_Page_1_kcwt8m.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369314/My_Favorite_Movie_Page_1_kcwt8m.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369316/My_Favorite_Movie_Page_2_tyxmey.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369319/My_Favorite_Movie_Page_3_tpug7c.png",
    ],
    features: [
      "Movie Title & Description",
      "Anchor Tags (Links)",
      "Movie Poster Image",
      "Local Video",
      "Local Audio",
      "YouTube Trailer Embed",
      "Cast Section",
      "Clean HTML Structure",
    ],
    technologies: [
      "HTML",
    ],
    title: "My Favorite Movie Page",
    description:
      "This project is an HTML-based movie webpage that showcases my favorite film. It includes a movie title, description, images, links, and multimedia elements such as video, audio, and an embedded YouTube trailer. The page also uses anchor tags for navigation and features a cast section with a list of main actors. This project helps practice essential HTML concepts like images, videos, audio, iframes, and internal/external linking.",
    category: "html",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/My_Favourite_Movie_Page_H",
  },
  {
    id: 3,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369353/Restaurant_Webpage_1_e7qhk5.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369353/Restaurant_Webpage_1_e7qhk5.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369356/Restaurant_Webpage_2_x37vid.png",
    ],
    features: [
      "Semantic Navigation Bar",
      "Header Section",
      "Main Content Using <main>",
      "About Section",
      "Menu Section",
      "Opening Hours Table",
      "Contact Section",
      "Footer Section",
      "Well-organized Content",
    ],
    technologies: [
      "HTML",
    ],
    title: "Restaurant Webpage",
    description:
      "This project is a fully structured restaurant webpage created using semantic HTML. It showcases a fictional restaurant and includes sections for navigation, an about page, menu items, opening hours, and contact information. The project focuses on using semantic tags such as <nav>, <header>, <main>, <section>, <article>, <footer>, and proper HTML elements like tables, lists, and spans. It demonstrates strong understanding of HTML structure, layout organization, and content grouping.",
    category: "html",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Restaurant_Webpage_H",
  },
  {
    id: 4,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369340/Event_Registration_Form_wy06fv.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369340/Event_Registration_Form_wy06fv.png",
    ],
    features: [
      "User Information Fields",
      "Gender Selection (Radio Buttons)",
      "Interests Selection (Checkboxes)",
      "Experience Level Dropdown",
      "Favorite Session Using Datalist",
      "About Section (Multiline Input)",
      "Submit Button",
      "Clean Layout and Readable Structure",
    ],
    technologies: [
      "HTML",
    ],
    title: "Event Registration Form",
    description:
      "This project is a fully functional event registration form built using HTML. It collects essential participant details such as name, email, gender, interests, experience level, and preferred sessions. The form includes a variety of HTML input types like text fields, email, password, radio buttons, checkboxes, dropdowns, datalists, textareas, and a submit button. It demonstrates strong foundational skills in creating structured, user-friendly forms using core HTML elements.",
    category: "html",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Event_Registration_Form_H",
  },
  {
    id: 5,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797467/Personal_Profile_Card_ij7fao.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797467/Personal_Profile_Card_ij7fao.png",
    ],
    features: [
      "Clean and Modern Card Layout",
      "Name and Role Display",
      "Scrollable Description Box",
      "Skills List",
      "Call-To-Action Button",
      "Responsive & Centered Design",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "Personal Profile Card",
    description:
      "This project is a simple and modern Profile Card created using HTML and CSS. It showcases a user’s name, profession, a short description, skills, and a call-to-action button. The layout demonstrates clean styling, spacing, scrollable text, and basic UI component design. It’s a good beginner project for learning how to create reusable profile components in websites or portfolios.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Personal_Profile_Card_HC",
  },
  {
    id: 6,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369320/Coffee_Shop_Menu_1_nhx32l.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369320/Coffee_Shop_Menu_1_nhx32l.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369314/Coffee_Shop_Menu_2_g9medj.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369311/Coffee_Shop_Menu_3_d6tvqr.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369320/Coffee_Shop_Menu_4_i8k8u9.png",
    ],
    features: [
      "Hero Banner Section",
      "Menu Sections (Signature Drinks & Classic Favourites)",
      "Stylish Typography",
      "Modern UI Styling",
      "Footer Section",
      "Responsive & Well-Structured Layout",
      "Image Optimization",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "Coffee Shop Menu",
    description:
      "This project is a beautifully designed Coffee Menu webpage for a fictional café. It uses HTML and CSS to showcase signature drinks, classic favorites, a hero banner, and a footer section with location and hours. The design includes modern styling techniques such as gradients, custom typography, shadows, and responsive layout elements. The page demonstrates structured content, elegant typography, and a polished UI suitable for restaurant or café websites.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Coffee_Shop_Menu_HC",
  },
  {
    id: 7,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796862/Interactive_Profile_Card_1_gimgjs.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796862/Interactive_Profile_Card_1_gimgjs.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796936/Interactive_Profile_Card_2_q9vanb.png",
    ],
    features: [
      "Centered Profile Card Layout",
      "Profile Image Display",
      "Interactive “Connect” Button",
      "Stats Footer with Decorative Line",
      "Card Hover Animation",
      "Smooth Transitions",
      "Clean UI + Modern Design Principles",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "Interactive Profile Card",
    description:
      "This project is an interactive profile card built using HTML and CSS. It displays a user’s profile picture, name, title, and social stats, along with a “Connect” button. The design includes modern UI techniques such as hover effects, transitions, transforms, pseudo-elements, and box-model styling. The card smoothly animates when hovered and features a clean, minimal, professional layout suitable for portfolios, user profiles, or social media UIs.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Interactive_Profile_Card_HC",
  },
  {
    id: 8,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797638/Responsive_Card_Layout_2_ngcxug.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797547/Responsive_Card_Layout_1_clbb1v.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797638/Responsive_Card_Layout_2_ngcxug.png",
    ],
    features: [
      "Mobile-First Design",
      "Responsive Flexbox Layout",
      "Modern UI Aesthetics",
      "Image Optimization",
      "Fully Expandable Component",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "Responsive Card Layout",
    description:
      "A simple, modern portfolio card built with HTML and CSS using a mobile-first approach. The layout stacks vertically on small screens and automatically shifts into a side-by-side design on larger screens using Flexbox and media queries. This component is ideal for showcasing developer profiles, team members, or portfolio sections.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Responsive_Card_Layout_HC",
  },
  {
    id: 9,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369366/Fashion_Store_1_gov01m.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369366/Fashion_Store_1_gov01m.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369347/Fashion_Store_2_yuva7t.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369351/Fashion_Store_3_dxte7c.png",
    ],
    features: [
      "Product Categories Section",
      "Upcoming Festival Sales Table",
      "Promotional Banner",
      "Information Section",
      "Simple, Clean Header and Footer",
      "Organized, Beginner-Friendly CSS",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "Fashion Store – Static E-Commerce Webpage",
    description:
      "This project is a static, fully structured fashion store webpage built using HTML and CSS. It displays product categories, upcoming festival sales, and store information in a clean, organized layout. The project demonstrates UI structuring, table-based layouts, image placement, styling, and content formatting—ideal for beginners learning front-end development essentials.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Fashion_Store_Web_Page_HC",
  },
  {
    id: 10,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369300/Chef_s_Hotel_1_blqkjx.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369300/Chef_s_Hotel_1_blqkjx.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369304/Chef_s_Hotel_2_bi851j.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369325/Chef_s_Hotel_3_ni8dig.png",
    ],
    features: [
      "Elegant Landing Section",
      "Room Types & Pricing Tables",
      "Visual Theme & Typography",
      "Footer Section",
      "Call-to-Action",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "Chef’s Hotel – Static Luxury Hotel Webpage",
    description:
      "This project is a beautifully designed static hotel webpage created using HTML and CSS. It showcases a luxury hotel with an elegant landing section, detailed room options, pricing tables, and a call-to-action for booking. The layout highlights strong UI structure, table formatting, typography, and visual design—ideal for beginners showcasing their front-end development skills.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Chef-s_Hotel_Web_Page_HC",
  },
  {
    id: 11,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369375/Foodie_1_sx2ekn.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369375/Foodie_1_sx2ekn.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369380/Foodie_2_emdlwc.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369362/Foodie_3_fzs0tc.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369369/Foodie_4_ymm59t.png",
    ],
    features: [
      "Clean Header Section",
      "Main Highlight Section",
      "Restaurant Showcase",
      "Food Rankings List",
      "Food Culture Section",
      "Food Price Table",
      "Simple Footer",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "Foodie – Online Food Delivery Webpage",
    description:
      "This project is a static food-delivery themed webpage built with HTML and CSS. It highlights popular restaurants in Delhi, showcases trending dishes, displays food rankings, and includes informational sections about Delhi’s food culture. The layout combines images, tables, and structured content to create a visually appealing and beginner-friendly front-end design.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Foodie_platform_Web_Page_HC",
  },
  {
    id: 12,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369337/course_syllabus_page_1_rexirn.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369337/course_syllabus_page_1_rexirn.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369339/course_syllabus_page_2_y8qrn3.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369332/course_syllabus_page_3_yfqho5.png",
    ],
    features: [
      "Professional Header & Navigation",
      "Course Introduction Section",
      "Course Overview Section",
      "Weekly Course Schedule",
      "Side-by-Side Layout",
      "Footer Section",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "Course Syllabus Webpage",
    description:
      "This project is a structured and educational course syllabus webpage built using HTML and CSS. It includes a professional header with navigation, an introductory section, a visual HTML preview image, a complete course overview, and a detailed weekly schedule. The layout demonstrates clean structuring, table formatting, use of semantic tags, and basic responsive alignment—perfect for beginners practicing front-end development.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Course_Syllabus_Web_Page_HC",
  },
  {
    id: 13,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369379/Hospital_Webpage_2_mh8q53.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369377/Hospital_Webpage_1_pfqvnz.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369379/Hospital_Webpage_2_mh8q53.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369290/Hospital_Webpage_3_i8cnpa.png",
    ],
    features: [
      "Clean Header & Navigation Bar",
      "Introduction & About Section",
      "Achievements & Success Stories",
      "Hospital Image Display",
      "Approved Doctors Table",
      "Improvement Ideas Table",
      "Daily Cured Patients Highlight",
      "User-Friendly Layout & Styling",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "Hospital Webpage",
    description:
      "This project is a static hospital management webpage built using HTML and CSS. It presents an overview of an Hospital, including its services, achievements, approved doctors, improvement ideas, and daily patient recovery statistics. The design uses clean layouts, structured tables, smooth navigation, and accessible content formatting, making it a great front-end practice project.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Hospital_Webpage_HC",
  },
  {
    id: 14,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369305/Beans_and_Brews_Cafe_2_jvyrtc.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369302/Beans_and_Brews_Cafe_1_z50bra.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369305/Beans_and_Brews_Cafe_2_jvyrtc.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369298/Beans_and_Brews_Cafe_3_iaumbu.png",
    ],
    features: [
      "Simple & Clean Navigation Bar",
      "Welcoming Home Section",
      "Menu Section with Image Banner",
      "About the Cafe Section",
      "Contact Section",
      "Footer Section",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "Beans and Brews Cafe",
    description:
      "This project is a simple, clean, and well-structured cafe website built using HTML and CSS. It presents a modern homepage, a menu section with images, an about section, and contact details—all wrapped in a clean layout suitable for small businesses or portfolio demonstration. The project showcases basic web design structure, navigation design, responsive section layouts, and content organization.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Cafe_Web_Page_HC",
  },
  {
    id: 15,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369370/Get_Fit_2_jjqv74.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369368/Get_Fit_1_uf8lfa.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369370/Get_Fit_2_jjqv74.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369371/Get_Fit_3_igujwl.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369371/Get_Fit_4_djinky.png",
    ],
    features: [
      "Hero Section with Welcome Message",
      "About Us Section",
      "Workout Routines Table",
      "Fitness Equipment Section",
      "Fitness Tips Section",
      "Consistent Visual Theme",
      "Organized Layout",
      "Footer",
    ],
    technologies: [
      "HTML",
      "CSS",
    ],
    title: "My Fitness Tips – Health & Workout Webpage",
    description:
      "This project is a structured and beginner-friendly fitness webpage built using HTML and CSS. It includes a welcoming hero section, an introduction to the platform, detailed workout routines, fitness equipment information, and helpful fitness tips for beginners. The design is clear, easy to navigate, and ideal for showcasing front-end skills related to layout, typography, table formatting, structured content, and responsive-friendly sections.",
    category: "htmlcss",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Get_Fit_Web_Page_HC",
  },
  {
    id: 16,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797013/Interactive_Profile_Card_JS_hi0zld.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797013/Interactive_Profile_Card_JS_hi0zld.png",
    ],
    features: [
      "Clean & Modern Profile Card UI",
      "Dynamic Text Updates with JavaScript",
      "Interactive Theme Transformation",
      "Smooth Visual Effects",
      "Neat, Minimal, and Responsive Layout",
    ],
    technologies: [
      "HTML",
      "CSS",
      "JS",
    ],
    title: "Interactive Profile Card",
    description:
      "This project is a modern, visually appealing profile card built using HTML, CSS, and JavaScript. It displays a user avatar, name, bio, and a theme label while dynamically updating the card’s content and appearance using JavaScript. The card includes a fun “theme switch” style effect, transforming the card into a vibrant, playful design mode. This project is great for beginners learning DOM manipulation, styling, and interactive UI components.",
    category: "javascript",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Interactive_Profile_Card_JS",
  },
  {
    id: 17,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369300/Interactive_Quiz_Form_1_nct8tk.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369300/Interactive_Quiz_Form_1_nct8tk.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369301/Interactive_Quiz_Form_2_htqopv.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369303/Interactive_Quiz_Form_3_bnsifj.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369304/Interactive_Quiz_Form_4_xrdkm8.png",
    ],
    features: [
      "Clean and Modern UI",
      "Interactive Hint System",
      "Full Form Validation",
      "Automatic Scoring System",
      "Smart Feedback Messages",
      "Color-Coded Result Display",
      "Responsive Layout",
    ],
    technologies: [
      "HTML",
      "CSS",
      "JS",
    ],
    title: "Interactive JavaScript Quiz Form",
    description:
      "This project is an interactive quiz application built using HTML, CSS, and JavaScript. It presents a 3-question multiple-choice quiz on JavaScript basics and includes dynamic hint toggles, form validation, score calculation, and responsive visual feedback. The clean UI, structured layout, and interactive behavior make it an excellent beginner-friendly project for learning DOM manipulation, event handling, and form logic.",
    category: "javascript",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Interactive_Quiz_Form_JS",
  },
  {
    id: 18,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796554/Dynamic_Bookmark_Manager_1_v7nu5z.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796554/Dynamic_Bookmark_Manager_1_v7nu5z.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796625/Dynamic_Bookmark_Manager_2_mazm19.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796695/Dynamic_Bookmark_Manager_3_ceb1b5.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796778/Dynamic_Bookmark_Manager_4_djjewt.png",
    ],
    features: [
      "Add Bookmarks Dynamically",
      "Input Validation",
      "Delete Bookmarks Instantly",
      "Clean & Modern User Interface",
      "Event Delegation for Efficient Performance",
      "Real-Time DOM Manipulation",
      "Fully Client-Side Application",
    ],
    technologies: [
      "HTML",
      "CSS",
      "JS",
    ],
    title: "Dynamic Bookmark Manager",
    description:
      "This project is a fully interactive Bookmark Manager built with HTML, CSS, and JavaScript. It allows users to quickly add, display, and delete bookmarks in real time without reloading the page. With a clean UI and smooth interactions, this project demonstrates DOM manipulation, event handling, form validation, and event delegation",
    category: "javascript",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Dynamic_Bookmark_Manager_JS",
  },
  {
    id: 19,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797191/Persistent_Product_Wishlist_2_g5joew.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797116/Persistent_Product_Wishlist_1_ft3d8k.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797191/Persistent_Product_Wishlist_2_g5joew.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797287/Persistent_Product_Wishlist_3_mbh5up.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797387/Persistent_Product_Wishlist_4_ahlhbq.png",
    ],
    features: [
      "Add Products to Wishlist Dynamically",
      "Persistent Data Using LocalStorage",
      "Stylish Product Card Layout",
      "Delete Products Instantly",
      "Event Delegation for Better Performance",
      "Automatic Wishlist Rendering on Page Load",
      "Real-World JavaScript Concepts",
    ],
    technologies: [
      "HTML",
      "CSS",
      "JS",
    ],
    title: "Persistent Product Wishlist",
    description:
      "This project is a fully interactive Product Wishlist Manager built using HTML, CSS, and JavaScript with LocalStorage. It allows users to add products (name, price, and image), display them in a clean card layout, and delete them when needed. The key feature of this project is data persistence, meaning all wishlist items remain saved even after the page is refreshed—thanks to LocalStorage. This makes it a perfect project for practicing DOM manipulation, data storage, event delegation, and dynamic UI rendering.",
    category: "javascript",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Persistent_Notes_App_JS",
  },
  {
    id: 20,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797722/Smart_Task_Tracker_1_d4tsoh.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797722/Smart_Task_Tracker_1_d4tsoh.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797847/Smart_Task_Tracker_2_pb79dj.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765797933/Smart_Task_Tracker_3_ycklnq.png",
    ],
    features: [
      "Add Tasks with Categories",
      "Fully Persistent Data (LocalStorage)",
      "Mark Tasks as Completed",
      "Delete Tasks Instantly",
      "Category-Based Filtering",
      "Dynamic, Real-Time DOM Rendering",
      "Event Delegation for Efficient Performance",
      "Helpful Feedback Messages",
      "Structured & Scalable Codebase",
    ],
    technologies: [
      "HTML",
      "CSS",
      "JS",
    ],
    title: "Smart Task Tracker",
    description:
      "The Smart Task Tracker is a feature-rich task-management web app built using HTML, CSS, and JavaScript with LocalStorage persistence. It allows users to create tasks, assign categories, mark tasks as completed, delete them, and automatically save everything in the browser—even after refreshing the page. This project demonstrates core concepts of DOM manipulation, event delegation, and real-world application behavior through persistent data storage and interactive UI updates.",
    category: "javascript",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Smart_Task_Tracker_JS",
  },
  {
    id: 21,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369289/Interactive_Forms_with_Dynamic_Tabs_1_et429a.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369289/Interactive_Forms_with_Dynamic_Tabs_1_et429a.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369289/Interactive_Forms_with_Dynamic_Tabs_3_lmm6jl.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369294/Interactive_Forms_with_Dynamic_Tabs_4_mfator.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369294/Interactive_Forms_with_Dynamic_Tabs_5_tmbsew.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369295/Interactive_Forms_with_Dynamic_Tabs_6_qlmc7d.png",
    ],
    features: [
      "Multi-Step Form with Tabs",
      "Robust Field Validation",
      "Clean, Professional UI/UX",
      "Smart Navigation Logic",
      "Terms & Conditions Confirmation",
      "Confirmation Screen",
      "Fully Controlled Form Inputs",
      "Modular, Scalable Architecture",
    ],
    technologies: [
      "React (component-based architecture)",
      "CSS (custom styling for tabs, transitions, layout)",
      "useState (state management for form data, errors, navigation)",
      "Vite (bundler + development server)",
      "ES Modules (modern import/export structure)",
    ],
    title: "Interactive Job Application Form with Dynamic Tabs",
    description:
      "This project is a fully interactive, multi-step Job Application Form built using React. It guides users through a structured 3-step form process—Personal Information, Experience, and Review & Submit—using a tabbed UI with validation, navigation controls, and a polished user experience. Each step validates its fields before allowing the user to move forward, ensuring clean data collection and improved usability. The project showcases advanced concepts including dynamic tab navigation, controlled components, multi-stage validation, form state management, conditional rendering, and submission success screens—all wrapped in a clean, responsive UI.",
    category: "react",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Interactive_Job_Application_Form_with_Dynamic_Tabs_React",
  },
  {
    id: 22,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369349/First_portfolio_1_ojqcrl.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369349/First_portfolio_1_ojqcrl.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369354/First_portfolio_2_eyua0m.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369378/First_portfolio_3_xzpmrn.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369363/First_portfolio_4_nvwhxa.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369359/First_portfolio_5_jamuug.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369363/First_portfolio_6_zsu8gu.png",
    ],
    features: [
      "Fully Responsive UI",
      "Component-Based Architecture",
      "Sticky & Modern Navigation Bar",
      "Custom CSS Design System",
      "Beautiful Hero Section",
      "About Section with Skills",
      "Projects Showcase",
      "Contact Section",
      "Blog Section Ready (Optional)",
      "Clean File Structure",
    ],
    technologies: [
      "React (component-based architecture for modular UI)",
      "useState Hook (state management inside components when needed)",
      "CSS (custom styling system with variables, responsiveness & animations)",
      "Vite (fast bundler + dev server for modern React apps)",
      "ES Modules (clean modular import/export structure)",
    ],
    title: "Modern React Portfolio Website",
    description:
      "This project is a fully responsive and professionally designed portfolio website built using React and modern frontend best practices. It includes multiple reusable components, dynamic styling, modular sections, and a polished UI created with a custom CSS design system. The website serves as a personal brand presence—showcasing your skills, projects, biography, and contact information—while maintaining a clean, elegant, and accessible layout optimized for all screen sizes.",
    category: "react",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/portfolio_react",
  },
  {
    id: 23,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796233/2048_Game_1_d3ghc5.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796233/2048_Game_1_d3ghc5.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796403/2048_Game_2_o4rqzx.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765796474/2048_Game_3_reg1wm.png",
    ],
    features: [
      "Fully Playable 2048 Mechanics",
      "Keyboard Controls",
      "Dynamic Board Rendering",
      "Game Over Detection",
      "Restart Button",
      "Styled Tiles with Colors",
      "Immutable State Logic",
    ],
    technologies: [
      "React (component-based UI + rendering the game board)",
      "useState Hook (managing board state and game-over state)",
      "useEffect Hook (listening for keyboard events)",
      "CSS (custom styling for grid, tiles, transitions, and animations)",
      "Vite (bundler + fast development environment)",
      "ES Modules (modern import/export structure)",
    ],
    title: "2048 Game",
    description:
      "This project is a fully functional 2048 puzzle game built using React. It recreates the classic sliding tile game where players merge identical numbers to reach 2048, featuring smooth tile movement, merging logic, keyboard controls, and full game-over detection. The game grid updates dynamically using React state, offering a responsive and interactive experience. A Restart button is included for quick replayability.",
    category: "react",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/2048_Game_React",
  },
  {
    id: 24,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765798011/Tic_tac_toe_1_iek0z2.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765798011/Tic_tac_toe_1_iek0z2.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765798105/Tic_tac_toe_2_t9r8kg.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369369/Tic_tac_toe_3_rft6ob.png",
    ],
    features: [
      "Fully Functional Tic-Tac-Toe Logic",
      "Winner Detection System",
      "Move History + Time Travel",
      "Game Restart & Step Navigation",
      "Clean & Responsive UI",
    ],
    technologies: [
      "React (component-based structure with Board, Game, Square components)",
      "useState Hook (managing board state, game moves, player turns)",
      "JavaScript (ES Modules) (modular functions like calculateWinner)",
      "CSS (styling for board grid, tiles, animations, layout)",
      "Vite (lightweight, fast dev environment & bundler)",
    ],
    title: "Tic-Tac-Toe game",
    description:
      "This project is a fully interactive Tic-Tac-Toe game built using React. It features a responsive 3×3 game board, player turn tracking, winner detection, and full move-history functionality—allowing players to “time travel” to any previous move. The UI is clean, minimal, and optimized for quick and intuitive gameplay. The project demonstrates core React concepts such as state management, props, immutability, and component-based architecture.",
    category: "react",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/Tic_tac_toe_React",
  },
  {
    id: 25,
    mainImage: "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369318/original_portfolio_2_epqwuc.png",
    img: [
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369318/original_portfolio_1_qv6xnn.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369318/original_portfolio_2_epqwuc.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369320/original_portfolio_3_svstqp.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369322/original_portfolio_4_vwqzz5.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369344/original_portfolio_5_zqoipo.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369326/original_portfolio_6_lk5bnz.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369344/original_portfolio_7_oxug6c.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369331/original_portfolio_8_iuuafe.png",
      "https://res.cloudinary.com/dgh3azwdo/image/upload/v1765369341/original_portfolio_9_of8txr.png",
    ],
    features: [
      "Modern & Responsive UI",
      "Smooth Scroll Animations",
      "Modular Component Architecture",
      "Dynamic Project System",
      "Project Details Page",
      "Working Contact Form (EmailJS)",
      "Experience Section (Timeline)",
      "Skills Grid with Icon Library",
      "Navbar + Footer",
      "Performance & Routing",
    ],
    technologies: [
      "React (component-based UI)",
      "useState (state management)",
      "useEffect (side effects & triggers)",
      "react-router-dom (routing & navigation)",
      "Tailwind CSS (utility-first styling)",
      "Framer Motion (animations & transitions)",
      "react-intersection-observer (scroll-triggered animations)",
      "Lottie React (JSON animations)",
      "EmailJS (send form data)",
      "React Icons (icons library)",
      "Vite (fast dev environment)",
      "ES Modules (modern imports)",
    ],
    title: "My Web Portfolio",
    description:
      "MyWebPortfolio is a modern, interactive, and performance-optimized developer portfolio built using React and Tailwind CSS. It showcases your skills, experience, and professional projects with smooth animations, category filters, dynamic routing, and Lottie-based visuals. The website delivers a premium UI/UX through scroll-triggered animations, responsive layouts, and a clean dark theme. It also supports project detail pages, a fully functional contact form via EmailJS, and a modular component-based structure following best React practices.",
    category: "react",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/portfolio2",
  },
  {
    id: 26,
    mainImage: "",
    img: [
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    features: [
      "Full CRUD Functionality",
      "Image Upload Support",
      "Redux Toolkit State Management",
      "REST API + MongoDB Backend",
      "Clean & Responsive UI",
      "Real-Time Feed Updates",
      "Smooth Component Structure",
      "Modular folder structure",
    ],
    technologies: [
      "React (component-based UI)",
      "Redux Toolkit (global state management)",
      "Axios (API communication)",
      "Material-UI (prebuilt UI components)",
      "useState / useEffect (React hooks for UI state)",
      "Vite (fast bundler + dev server)",
      "ES Modules (import/export structure)",
      "Node.js + Express.js (REST API)",
      "MongoDB Atlas (cloud database)",
      "Mongoose (schema + model)",
      "CORS / Body-Parser (middleware)",
      "Nodemon (auto server reload)",
    ],
    title: "Golden Frames",
    description:
      "Golden Frames is a MERN-stack photo-memory sharing app where user can post memorable moments with a title, message, tags, and an image. Users can interact with posts through likes, updates, and deletion.The app uses Redux Toolkit for global state management, Axios for API communication, Material-UI for UI components, MongoDB Atlas for cloud storage, and Express.js for building RESTful backend APIs. All posts are stored in MongoDB and are rendered dynamically on the UI with smooth re-render and state updates.",
    category: "mern",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/golden_frames_v2_MERN",
  },
  {
    id: 27,
    mainImage: "",
    img: [
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    features: [
      "User Authentication & Authorization",
      "AI Image Generation",
      "Credit-Based System",
      "User Dashboard & Gallery",
      "Modern UI + Smooth Animations",
      "Performance",
      "Security",
    ],
    technologies: [
      "React (UI components + routing)",
      "Context API (global state management)",
      "TailwindCSS (styling)",
      "Framer Motion (animations)",
      "Lottie Files (interactive visuals)",
      "Axios (API communication)",
      "Vite (bundler + dev server)",
      "Node.js (server runtime)",
      "Express (API routes + middleware)",
      "MongoDB + Mongoose (database + schemas)",
      "JWT (authentication)",
      "bcryptjs (password hashing)",
      "ClipDrop API (AI image generation)",
      "CORS & dotenv (server config)",
      "REST API Architecture",
    ],
    title: "AI_MagicLens (In progress)",
    description:
      "Imagify is a full-stack AI Image Generation and Management platform built with the MERN stack. It allows users to generate AI-powered images, manage galleries, buy credits, download results, and securely store user data. The project includes a complete authentication system, credit-based usage limits, a responsive modern UI, and integration with the ClipDrop AI API for high-quality images.",
    category: "mern",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/AI_MagicLens",
  },
  {
    id: 28,
    mainImage: "",
    img: [
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    features: [
      "Secure User Authentication & Authorization",
      "Student Dashboard & Learning Panel",
      "Instructor Course Management System",
      "Full Course Creation & Curriculum Builder",
      "Cloud Media Upload (Videos, Images, Docs)",
      "Integrated Online Payments (Razorpay)",
      "Video-Based Learning with Progress Tracking",
      "Course Ratings & Reviews System",
      "Wishlist & Shopping Cart Flow",
      "Enrollment & Access Control for Premium Courses",
      "User Profile & Account Settings Management",
      "Insights & Analytics for Instructors",
      "Dynamic Home, Catalog, and Course Detail Pages",
      "Admin-like Controls for Categories & Course Structure",
      "Modern Responsive UI with Animations (Framer Motion)",
      "Fast Performance with Lazy Loading & Optimized Media",
      "Robust Backend APIs (Node + Express + MongoDB)",
    ],
    technologies: [
      "React (UI components, routing)",
      "React Router (navigation)",
      "Redux Toolkit (state management)",
      "TailwindCSS (utility-first styling)",
      "Framer Motion (animations)",
      "React Hook Form (form handling)",
      "React Dropzone (file upload)",
      "React Hot Toast (notifications)",
      "Chart.js (analytics charts)",
      "Video React (video player)",
      "Lazy Load Image Component (image optimization)",
      "Vite (development server + bundler)",
      "Node.js (runtime)",
      "Express.js (server framework)",
      "MongoDB + Mongoose (database & schema modeling)",
      "JWT (authentication)",
      "Cloudinary SDK (media uploads)",
      "Razorpay SDK (payments)",
      "Nodemailer (email service)",
      "Bcrypt.js (password hashing)",
      "CORS (security)",
      "Body-Parser (API parsing)",
    ],
    title: "TutorX (In progress)",
    description:
      "TutorX is a full-fledged MERN stack online learning platform where students can explore, purchase, and learn from structured courses, while instructors can create and manage educational content. The platform integrates powerful features like secure authentication, cloud media handling, real payment gateway integration, analytics dashboards, and a modern, responsive UI optimized for learning. It uses Cloudinary for storing course media, Razorpay for secure payments, and MongoDB for managing all user & course data. The architecture follows industry standards with modular routing, controllers, middleware, and reusable services—making it scalable and production-ready.",
    category: "mern",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/TutorX",
  },
  {
    id: 29,
    mainImage: "",
    img: [
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    features: [
      "User Accounts",
      "Shopping Cart",
      "Save For Later",
      "Wishlist",
      "Product Browsing",
      "Checkout & Payments",
      "Orders System",
      "Product Reviews",
      "Admin Dashboard",
      "Media & Email Services",
    ],
    technologies: [
      "React (UI components)",
      "React Router (page navigation)",
      "Redux (global state)",
      "TailwindCSS (utility styling)",
      "MUI (UI components)",
      "Chart.js (admin analytics)",
      "Node.js (server runtime)",
      "Express.js (API routing)",
      "MongoDB + Mongoose (database & schema)",
      "JWT (authentication)",
      "Paytm (payment gateway)",
      "Cloudinary (image storage)",
      "SendGrid (email service)",
    ],
    title: "flipkart_clone (In progress)",
    description:
      "A production-grade Flipkart-style e-commerce application built using the MERN stack, complete with a full admin dashboard, Paytm payment gateway, advanced product filtering, and complete user shopping features. This project replicates real-world e-commerce flows — browsing, wishlisting, cart management, checkout, payment, order tracking, admin product management, and more.",
    category: "mern",
    liveLink: "",
    codeLink: "https://github.com/ronikjoshi/flipkart_clone",
  },
];

export default Items;